### PR TITLE
Exit with non-zero status code on failure

### LINKED ISSUE #228: eps should exit with error status code after "Unable to find .cookie file, try setting `datadir` config"
eps v0.2.1.1 on Debian Sid.
bitcoind v0.20.1 from Debian repos.

I am launching `eps` on boot as `systemd` unit (same with `bitcoind`). After system booted, I have to start `eps` again (this time manually) if I want to use `Electrum`. It seems that it does not report error when exiting (via exit status), and so `systemd` does not restart it as configured:
```
$ sudo systemctl status eps
● eps.service - Electrum Personal Server
     Loaded: loaded (/etc/systemd/system/eps.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Sun 2020-12-20 12:00:33 EET; 58min ago
    Process: 730 ExecStartPre=rm /home/eps/log.txt (code=exited, status=0/SUCCESS)
    Process: 761 ExecStart=/opt/python3_venv_eps/bin/electrum-personal-server /home/eps/config.ini (code=exited, status=0/SUCCESS)
   Main PID: 761 (code=exited, status=0/SUCCESS)

gruod. 20 12:00:32 vinco systemd[1]: Starting Electrum Personal Server...
gruod. 20 12:00:32 vinco systemd[1]: Started Electrum Personal Server.
gruod. 20 12:00:33 vinco eps[761]: INFO:2020-12-20 12:00:33,238: Starting Electrum Personal Server 0.2.1.1
gruod. 20 12:00:33 vinco eps[761]: INFO:2020-12-20 12:00:33,239: Logging to /home/eps/log.txt
gruod. 20 12:00:33 vinco eps[761]: WARNING:2020-12-20 12:00:33,239: Unable to find .cookie file, try setting `datadir` config
gruod. 20 12:00:33 vinco systemd[1]: eps.service: Succeeded.
```
Note this:
` Active: inactive (dead)`
and:
`(code=exited, status=0/SUCCESS)`

Failure seems expected, as `bitcoind` takes time to fully start. It would be better that `eps` would just exit with 1 or any other non-zero status code.

### PR DESCRIPTION
**Pull request by Talkless**
Closes #228

This is how it works after changes:
```
Dec 24 13:49:11 vinco systemd[1]: Starting Electrum Personal Server...
Dec 24 13:49:11 vinco systemd[1]: Started Electrum Personal Server.
Dec 24 13:49:11 vinco eps[19385]: INFO:2020-12-24 13:49:11,344: Starting Electrum Personal Server 0.2.1.1
Dec 24 13:49:11 vinco eps[19385]: INFO:2020-12-24 13:49:11,344: Logging to /home/eps/log.txt
Dec 24 13:49:11 vinco eps[19385]: WARNING:2020-12-24 13:49:11,344: Unable to find .cookie file, try setting `datadir` config
Dec 24 13:49:11 vinco systemd[1]: eps.service: Main process exited, code=exited, status=1/FAILURE
Dec 24 13:49:11 vinco systemd[1]: eps.service: Failed with result 'exit-code'.
Dec 24 13:49:41 vinco systemd[1]: eps.service: Scheduled restart job, restart counter is at 1.
Dec 24 13:49:41 vinco systemd[1]: Stopped Electrum Personal Server.
Dec 24 13:49:41 vinco systemd[1]: Starting Electrum Personal Server...
Dec 24 13:49:41 vinco systemd[1]: Started Electrum Personal Server.
Dec 24 13:49:41 vinco eps[19632]: INFO:2020-12-24 13:49:41,520: Starting Electrum Personal Server 0.2.1.1
Dec 24 13:49:41 vinco eps[19632]: INFO:2020-12-24 13:49:41,521: Logging to /home/eps/log.txt
Dec 24 13:49:43 vinco eps[19632]: INFO:2020-12-24 13:49:43,733: Displaying first 3 addresses of each master public key:
Dec 24 13:49:43 vinco eps[19632]: INFO:2020-12-24 13:49:43,737:
```
`systemd` now restarts `eps` because of `Restart=on-failure` and `RestartSec=30` and the fact that `eps` now returns non-zero status code on failure while `bitcoind` is starting up.

### CODE REVIEW

**Comment by chris-belcher** [comment]
Thanks for the PR

Does this work as you'd expect when installing and running with pip?

I ask because of this https://github.com/chris-belcher/electrum-personal-server/blob/master/setup.py#L15 the entry point in those cases is the function main() rather than the `if __name__ == "__main__"` branch.

**Comment by Talkless** [comment]
> Does this work as you'd expect when installing and running with pip?

Hmm, I just applied these modifications manually in the already installed `/opt/python3_venv_eps/lib/python3.9/site-packages/electrumpersonalserver/server/common.py` file.

I need see where that `main()` is called...

**Comment by Talkless** [comment]
```
$ cat /opt/python3_venv_eps/bin/electrum-personal-server 
#!/opt/python3_venv_eps/bin/python
# EASY-INSTALL-ENTRY-SCRIPT: 'electrum-personal-server==0.2.0.dev0','console_scripts','electrum-personal-server'
__requires__ = 'electrum-personal-server==0.2.0.dev0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('electrum-personal-server==0.2.0.dev0', 'console_scripts', 'electrum-personal-server')()
    )
```
Looks like `bin/electrum-personal-server` uses `sys.exit()` already, so I guess that's why it works? I just accidentally made it work _also_ for the `pyinstaller`?

**Comment by chris-belcher** [comment]
If it already worked before, then why didn't your systemd setup from issue #228 work?

**Comment by Talkless** [comment]
> If it already worked before

It was not returning non-zero status code before? main() retruned nothing, I guess it's None in pythonb, and sys.exit() interpreted as 0?

**Comment by Talkless** [comment]
What I wanted to say is by fiddling with `__main__`-stuff, I also made it to return status code in `pyinstaller` use case. I didn't knew that this code was _only_ for `pyinstaller`.

**Comment by chris-belcher** [comment]
Ah OK got it. Merging

**Pull request merged**
