### PR TITLE
Update p2p user agent string to 22

### PR DESCRIPTION
**Pull request by andrewtoth**
Version 22 is now the most popular user agent of listening nodes https://bitnodes.io/nodes/, and trending to be the most popular overall very soon https://luke.dashjr.org/programs/bitcoin/files/charts/software.html.

### CODE REVIEW

**Comment by chris-belcher** [comment]
Thanks

**Comment by Derek701** [comment]
Should this change be Satoshi:22.0.0 instead of Satoshi:0.22.0?

**Comment by andrewtoth** [comment]
Oops yes, sorry.

**Comment by chris-belcher** [comment]
Derp, serves me right for merging so fast haha. No harm done just open another PR fixing it

**Comment by chris-belcher** [comment]
A thing I just thought of, you can actually obtain the user agent string from an RPC call, I think `getblockchaininfo`. It might be worth writing code which uses that user agent.

**Comment by andrewtoth** [comment]
> A thing I just thought of, you can actually obtain the user agent string from an RPC call, I think `getblockchaininfo`. It might be worth writing code which uses that user agent.

Well, if you're using a less popular version, it's more private to use the most popular one when broadcasting via tor instead right? You don't want to just use whatever your local version is.

**Pull request merged**
